stages:
  - test

test:
  stage: test
  image: node:14.15.4-alpine
  addons:
    chrome: stable
  script:
    - yarn install
    - yarn lint
    - yarn test && yarn test --project a-lib
  cache:
    paths:
      - node_modules
