stages:
  - test
  - build
  - staging

test:
  stage: test
  image: node:14.15.4-alpine
  before_script:
    - apk add chromium
  script:
    - yarn install
    - yarn lint
    - yarn test-ci
  cache:
    key: yarn-path
    paths:
      - node_modules

build:
  stage: build
  script:
    - yarn build-ci
  cache:
    key: yarn-path
    paths:
      - node_modules
  artifacts:
    paths:
      - dist/

docker:
  image: docker:latest
  stage: build
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin
